### ISSUE TITLE
Publish on a CDN for ease of use

### ISSUE THREAD

**Issue by Pamplemousse** [zaproxy/front-end-tracker#5]
It would be handy for people to be able to inject into their HTML directly, using something like:
```html
<script src='front-end-tracker.js'></script>
```

[UNPKG](https://unpkg.com/) is a web service serving content from npm.
As it is now, the version 1.0.0 of the `front-end-tracker` is published on there already: [unpkg.com/@zaproxy/front-end-tracker@1.0.0/](https://unpkg.com/@zaproxy/front-end-tracker@1.0.0/).
However, there is no bundled version to inject directly in the page.

One solution would be to have [travis](https://travis-ci.com/zaproxy/front-end-tracker) to run the build and push it to npm, without cleaning the generated `dist/` file ([see some example on my fork](https://github.com/Pamplemousse/front-end-tracker/commit/9f3beb092b93309e39dcc695fa3606e87093e9fd)).

Then, hopefully, this would work:
```html
<script src='https://unpkg.com/@zaproxy/front-end-tracker@1.0.0/dist/front-end-tracker.js'></script>
```

**Comment by Pamplemousse** [comment]
@psiinon, @thc202, #44 follow-up:

Would that be possible to tag a new version `v1.0.1` (on git) so the deploy will be triggered in Travis, for the minified content to be available [on unpkg](https://unpkg.com/browse/@zaproxy/front-end-tracker@1.0.1/)?

**Comment by thc202** [comment]
The version is currently `1.0.2`, should that be changed?

**Comment by Pamplemousse** [comment]
Oh, right, in the `package.json`.
Although, it has not been published [on npm](https://www.npmjs.com/package/@zaproxy/front-end-tracker)... Because Travis was not yet setup.

Let's have the `package.json` version and git tags match.

There have been a few commits since the `v1.0.2` tag, so maybe it let's bump the version to `1.0.3`:
  * commit the change in `package.json`
  * tag this commit to be `v1.0.3`

**Comment by thc202** [comment]
That works for me. You doing that?

**Comment by thc202** [comment]
Now published https://unpkg.com/browse/@zaproxy/front-end-tracker@1.0.3/dist/
